### PR TITLE
Upgrade libunftp and tokio

### PR DESCRIPTION
**Pull request by hannesdejager**
This MR upgrades libunftp from 0.14 to 0.17 and tokio from 0.3 to 1.0

### CODE REVIEW

**Comment by hannesdejager** [comment]
Hi @quark-zju, I was testing my changes now and thought my PR broke something (made the PR Draft because of it). But then I also installed the latest version from crates.io and I get this error with both:

```
crypted|⇒ x79d8 serve
Password:
Serving /Users/xxx/crypted at 127.0.0.2:2121
Error: server error: io error
```

I'm on macOS.

**Comment by quark-zju** [comment]
Hi, @hannesdejager! Thanks for the PR. I was able to upgraded all dependencies and it seems to work fine for me on Windows. I pushed my current changes in the `dev` branch.

Maybe you can set `X79D8_LOG=trace` to enable some debugging output to see what happened? Some OS might not free port immediately. In that case, picking a different address (like  `x79d8 serve -a 127.0.0.2:2122`) might help?

**Comment by hannesdejager** [comment]
Here is some log output:

```sh
⇒ X79D8_LOG=trace x79d8 serve
Password:
Serving /Users/xxx/crypted at 127.0.0.2:2121
[2021-03-27T23:33:22.349Z DEBUG x79d8::ftpfs] Flushing on drop
[2021-03-27T23:33:22.349Z INFO  x79d8::ftpfs] Writing changes to disk
Error: server error: io error
[2021-03-27T23:33:22.349Z DEBUG x79d8::ftpfs] Flushing on drop
[2021-03-27T23:33:22.349Z INFO  x79d8::ftpfs] Writing changes to disk
```

I've tried serving on a different port too but same result.

**Comment by quark-zju** [comment]
It seems macOS does not allow binding to `127.0.0.2`. I can reproduce using the older version (before tokio upgrade). Could you try `-a "127.0.0.1:2121"` and see if it solves the issue? It works for me.

I'll change the default address and make the error more verbose.

**Comment by hannesdejager** [comment]
Using `-a "127.0.0.1:2121"` works perfectly fine yes :-)

**Comment by hannesdejager** [comment]
I guess we can then close this PR because you already made the corresponding commit to your dev branch.

**Pull request closed without merging**
